/**
 * @description       : 
 * @author            : ChangeMeIn@tUserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-21-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   07-15-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class MyClass {
    public static void myMethod()
    {
        System.debug('Hello World18');
    }
}
